### ISSUE TITLE
Warning critical dependency

### ISSUE THREAD

**Issue by garmjs** [thejameskyle/react-loadable#10]
First of all James thanks for publishing this cool project 🙌 , i have tried and its working really good in SSR too, but i'm getting this warning in console and i don't know yet why! if anyone else is getting please let me know and if you did get rid of it.

```
WARNING in ./~/react-loadable/lib/index.js
31:24-41 Critical dependency: the request of a dependency is an expression
```

**Comment by simenbrekken** [comment]
@garmjs Are you storing the path to the module in a variable rather than doing it inline?

**Comment by navgarcha** [comment]
I'm getting the same issue but it appears to be a HMR error - perhaps they create a variable?

```
[HMR] bundle has 1 warnings
client.js:161 ./~/react-loadable/lib/index.js
31:24-41 Critical dependency: the request of a dependency is an expression
```

My code:

```
const Section = Loadable({
    loader: () => import('travel/containers/Section'),
    LoadingComponent,
    serverSideRequirePath: path.join(__dirname, '../../containers/Section'),
    webpackRequireWeakId: () => require.resolveWeak('travel/containers/Section')
});
```
(not i use a babel path resolver for those require strings)

**Comment by kentcdodds** [comment]
Actually, it's not an HMR error, the problem is related to https://github.com/webpack/webpack/issues/196 and is happening because of [this line](https://github.com/thejameskyle/react-loadable/blob/master/src/index.js#L16).

Unfortunately, I'm unsure of how to get around this. Any ideas welcome!

**Comment by kentcdodds** [comment]
ping @thelarkinn?

**Comment by benjamn** [comment]
What about [`__non_webpack_require__`](https://github.com/webpack/docs/wiki/api-in-modules#__non_webpack_require__)?

**Comment by kentcdodds** [comment]
Thanks for chiming in @benjamn! Does that work in node?

**Comment by kentcdodds** [comment]
FWIW, I verified that this is nothing more than an annoyance. All it adds to your bundle is this:

```javascript
/* 1 */
/***/ (function(module, exports) {

function webpackEmptyContext(req) {
	throw new Error("Cannot find module '" + req + "'.");
}
webpackEmptyContext.keys = function() { return []; };
webpackEmptyContext.resolve = webpackEmptyContext;
module.exports = webpackEmptyContext;
webpackEmptyContext.id = 1;


/***/ }),
```

**Comment by benjamn** [comment]
Alternatively, in Node you can do `babelInterop(module.require(pathOrId))`, which might be enough to make Webpack happy?

**Comment by kentcdodds** [comment]
Unfortunately that also won't work because we actually want that line of code to use node's require in the backend, and webpack's require in the browser. :-/ Not sure of a good way to solve this, but I'm sure this isn't the first module to have this problem!

**Comment by kentcdodds** [comment]
From ~StackOverflow~ Twitter (thanks @threepointone!)

```javascript
const nodeRequire = !isBrowser? eval(‘require’) : null
nodeRequire(expression) // won’t trigger webpack warning
```

Thoughts @thejameskyle? I'd gladly open a PR for this.

**Comment by kentcdodds** [comment]
Thinking about this more I think it'd be a bad idea to encode webpack-specific stuff into the tool... Thinking it may be better to come up with a different solution :-/

**Comment by kentcdodds** [comment]
On second (or third?) thought, as @threepointone mentioned to me [on twitter](https://twitter.com/threepointone/status/842093694778015749):

> the whole lib is webpack specific so I don't see how the comment is true

Yeah, so this is actually probably a fine solution. I'll make a PR and we can discuss over there.

**Comment by benjamn** [comment]
Trying to work better with Webpack (or any other module system) is fine, but I definitely wouldn't call `react-loadable` Webpack-specific: https://blog.meteor.com/meteor-1-5-react-loadable-f029a320e59c#.h8tb6nl8b

**Comment by kentcdodds** [comment]
Oh wow! Cool! I hope that what I have come up with will work for both of our use cases.

Turns out that this issue is actually a pretty significant issue. Please see [my PR](https://github.com/thejameskyle/react-loadable/pull/14) for more info! It gets rid of the original issue as well as the bigger issue we didn't realize existed :)
