### ISSUE TITLE
How about a webpack plugin that handles all the boilerplate code?

### ISSUE THREAD

**Issue by pke** [thejameskyle/react-loadable#11]
I wonder if we could have a webpack plugin that generates all the code you have to write manually now for weakId and server side path for us.

I don't know much about webpack plugins but maybe something like this signature is picked up by webpack (in C++ I'd write a macro):

```es6
const LoadableAnotherComponent = Loadable('./another-component', {
  LoadingComponent: MyLoadingComponent
});
``` 

and it gets transformed to: 

```es6
const LoadableAnotherComponent = Loadable({
  loader: () => import('./another-component'),
  LoadingComponent: MyLoadingComponent,
  serverSideRequirePath: path.join(__dirname, './another-component'),
  webpackRequireWeakId: () => require.resolveWeak('./another-component'),
});
```

btw: Why is `webpackRequireWeakId` a function and not just a field value like `loader` and `serverSideRequirePath` ?

**Comment by ctrlplusb** [comment]
I'd advise against having a transpilation plugin (babel/webpack etc) as it locks you to static representations of the components.  I made this mistake with a previous library I created.  Trust me, when you have a ton of route components or whatever you will praise the heavens that you can throw them through a mapping function to create a whole bunch of `Loadable` instances.

**Comment by navgarcha** [comment]
Regarding the `wepbackRequireWeakId` question see: https://github.com/thejameskyle/react-loadable/issues/8

**Comment by benjamn** [comment]
Echoing @ctrlplusb, this sounds like something that someone (not @thejameskyle, maybe you @pke? 😉) should write if they are so inspired. Magical Webpack-only syntactic sugar would be a strange addition to the core `react-loadable` library, IMO.

**Comment by thejameskyle** [comment]
You could do this pretty easily with a Babel plugin if you'd like. Although I would make it transform from something that's actually correct usage of the library:

```js
const LoadableAnotherComponent = Loadable({
  loader: () => import('./another-component'),
  LoadingComponent: MyLoadingComponent,
});
```

Although yeah, I don't want to do this as part of react loadable– at least not now
