### ISSUE TITLE
Return the promise from preload

### ISSUE THREAD

**Issue by EnoahNetzach** [thejameskyle/react-loadable#16]
Right now preloading doesn't return the internal `load()` promise, but it could be useful having it.

My use case is: I do server side rendering, the "route" chunks get loaded asynchronously, but I wait for the "above the fold" ones to get fully fetched prior to render the React app.
This way I don't lose server side rendered content while waiting for the chunks to arrive.

BTW: great job! ^_^

**Comment by thejameskyle** [comment]
Server-side rendering should not be depending on prefetching in any way. Everything should be required synchronously using [`opts.serverSideRequirePath`](https://github.com/thejameskyle/react-loadable#optsserversiderequirepath-optional). Not returning the promise was intentional because you shouldn't ever depend on prefetch succeeding sometime in the future.

**Comment by EnoahNetzach** [comment]
I'm not proposing this for using it during SSR, but on the client...

During SSR I use `opts.serverSideRequirePath`, as indicated, prior to *client* initialization, I *have* to wait for all the required chunks to be loaded.

**Comment by EnoahNetzach** [comment]
My bad for not having clearly specified that with 

>  the "route" chunks get loaded asynchronously

I meant on the client side 😉 .

**Comment by thejameskyle** [comment]
This is a known issue with react loadable, see https://medium.com/@thejameskyle/react-loadable-2674c59de178#1a48. I'm working on fixing this in a much better way

**Comment by EnoahNetzach** [comment]
Isn't that another problem?

In my webpack config I have a plugin that's dedicated to look for "route" chunks and those are passed down for adding them in the served html as `<link href="..." rel="preload" as="script">`.

Once that is done, my problem still remains: I need to wait for the `import()` "route" chunk promise to resolve prior to run react.

**Comment by thejameskyle** [comment]
You should not be waiting to run React is my point, you should run it immediately and let the loading state exist.

**Comment by EnoahNetzach** [comment]
But this way I lose all the server side rendered content for a while..

**Comment by thejameskyle** [comment]
Yeah, I want to solve this in better ways than deferring interactivity until everything is loading. It's better to have portions of the page frozen until the bundle is loaded. Not a lot is possible today, but I think we'll be able to do more with react fiber

**Comment by threepointone** [comment]
The trick here is to load the relevant chunks on the page before calling React.render. In order -
- html 
- js bundle
- chunks for the given page
- init()

**Comment by EnoahNetzach** [comment]
@threepointone sorry, are you suggesting that I have to do it manually, or that it should be done by preload?

**Comment by threepointone** [comment]
manually, with `<script>` tags. this will enable react-loadable to pick up the module synchronously and not lose server rendered content. 

what I'd do, is have this code in my bundle's entry point - 
```jsx
window.__init = function(){
  React.render(<App/>, document.getElementById('root'))
}
```
then include `<script>` tags corresponding to the chunks I'd want for that given html, 
and then *after* that, I'll have an inline script like - 
```jsx
<script>window.__init()</script>
```

another thing to note - you'll have to be able to tell *which* chunks emitted are the ones containing your views. so instead of using `import()`, use `require.ensure` for predictable chunk names, like so
```jsx
let LoadableMyComponent = Loadable({
  loader: () => require.ensure([], require => require('./MyComponent'), 'mycomponent'),
  // ... other stuff 
});

```

this should generate `mycomponent.chunk.js` (or something similar, can't recollect), which you then include with `<script>` tags after your bundle.

**Comment by EnoahNetzach** [comment]
@threepointone thanks, my problem is not the chunk generation/recognition. For that I use a static path (e.g. `src/routes`) and a custom webpack plugin.

The problem is that by using `<script>` I lose the possibility to download scripts asynchronously and in batch, waiting a lot more as a result.

In the end I think I'll have to handle this by doing:
- preload of the route chunks (` <link href="..." rel="preload" as="script">`)
- sync load of `vendors` and `main` (i.e. the static layer)
- load route chunks by injecting `script` tags in the DOM (i.e. the dynamic layer)
- wait for all injected script tags to have been loaded (by callbacks, usually one single route)
- run react
- ...
- profit (?)

It's more bloated, not using promises to the full extent, but it will do.

I could also experiment with preload in the `head` + sync load  at the very end of the `body`..

**Comment by threepointone** [comment]
Script tags load asynchronously and in parallel in most browsers, you don't have to worry about that. you can *also* include the `<link preload/>` tags in the `<head/>` as an optimization (they don't get evaled) along with script tags later in the body.

**Comment by EnoahNetzach** [comment]
I just did some tests.

### Modus operandi
- Production build, run with the same system (docker + nginx + node), locally;
- Chrome version 56;
- The first three full browser loads are discharged, the next six ones are considered;
- Every load is done with empty cache and hard reload;
- A full site load is awaited before beginning the next test run;
- Chrome Dev Tools "Finish", "Load" and "DOMContentLoaded" timings are used.

### Test cases
1. synchronous load + react run as last script (as suggested by https://github.com/thejameskyle/react-loadable/issues/16#issuecomment-287690606)
2. synchronous load + preload + react run as last script (as suggested by https://github.com/thejameskyle/react-loadable/issues/16#issuecomment-287711201)
3. "vendor" sync, "main" async, route chunks preloaded + react run when the `preload` Promise resolves (as I am proposing)

### Results
| (in seconds)     | DOM  | Load | Finish |
|----------------:|------|------|--------|
|        Promise | 1.9  | 3.07 | 3.13  |
|           Sync | 2.68 | 3.54 | 3.63   |
| Sync + preload | 2.56 | 3.52 | 3.64   |

### Conclusion
By returning a promise, every timing is ~500ms less than the other methods.

---

### Raw data
| (in seconds)     | DOM  | Load | Finish |
|----------------:|------|------|--------|
| Promise        | 2    | 4.11 | 4.17   |
|                | 1.84 | 2.83 | 2.88   |
|                | 1.87 | 3.05 | 3.1    |
|                | 2.07 | 3.1  | 3.17   |
|                | 1.64 | 2.57 | 2.6    |
|                | 1.96 | 2.74 | 2.86   |
| Sync           | 2.61 | 3.63 | 3.7    |
|                | 2.7  | 3.47 | 3.58   |
|                | 2.87 | 3.49 | 3.57   |
|                | 2.83 | 3.59 | 3.75   |
|                | 2.56 | 3.43 | 3.52   |
|                | 2.5  | 3.61 | 3.66   |
| Sync + preload | 2.97 | 4.14 | 4.24   |
|                | 2.12 | 3.29 | 3.41   |
|                | 2.32 | 3.39 | 3.46   |
|                | 3.42 | 3.25 | 3.37   |
|                | 2.28 | 3.29 | 3.42   |
|                | 2.27 | 3.76 | 3.96   |

**Comment by EnoahNetzach** [comment]
p.s.: I didn't intend to sound fussy, just meticulous 😛

**Comment by threepointone** [comment]
Looks neat. I'd love to see the setup, not sure I'm comprehending correctly. In any case, hope you've solved your usecase and it works

**Comment by garmjs** [comment]
is anyone getting `TypeError: flushServerSideRequires is not a function` 

import

```
const Loadable = require('react-loadable').default
const { flushServerSideRequires } = Loadable
```
