### ISSUE TITLE
Wondering if the API can be made simpler

### ISSUE THREAD

**Issue by soneymathew** [thejameskyle/react-loadable#19]
Really appreciate the effort put into this and huge thanks to you.
I was wondering if the API can be made simpler to avoid some of the boilerplate code that needs to be repeated vs assuming defaults

Maybe as a webpack loader or plugin or a transpile/transformation step ?

```
import LoadableMyComponent from 'loadable!./MyComponent';

export default class Application extends React.Component {
  render() {
    return <LoadableMyComponent/>;
  }
}
```

**Comment by thejameskyle** [comment]
I do not want to tie it that heavily to proprietary webpack APIs. I consider the `loader!./filename` usage a bad practice anyways.
