### ISSUE TITLE
Component never seems to load (react + typescript)

### ISSUE THREAD

**Issue by maierson** [thejameskyle/react-loadable#20]
We have an edit functionality in our app. It is only rarely used and controlled by a `BookEditor`. I want to code split to load the editor later. 

webpack config (needs the public path and chunkFilename to locate the script):

  ```
...
output: {
    filename: '[name].js',
    path: PATHS.build,
    publicPath: '/',
    chunkFilename: '[id].chunk.js'
  }
```
The chunk gets created as `0.chunk.js`.

The loadable component. BookEditorLoadable:

```
import * as React from 'react';

import Loadable from 'react-loadable';

// typescript needs this to use import()
declare global {
    interface System {
        import(request: string): Promise<any>
    }
    var System: System
}

interface Props {
    isLoading: boolean,
    error: Error | null,
    pastDelay: null,
};

let MyLoadingComponent = ({ isLoading, error, pastDelay }: Props) => {
    console.log('Loading component: ', isLoading, error, pastDelay);
    if (isLoading) {
        return pastDelay ? <div>Loading...</div> : null; // Don't flash "Loading..." when we don't need to.
    } if (error) {
        return <div>Error! Component failed to load</div>;
    } else {
        return null;
    }
};

const BookEditorLoadable = Loadable({
    loader: () => System.import('./BookEditor'),
    LoadingComponent: MyLoadingComponent,
    delay: 100
});

export default BookEditorLoadable;
```
And it is used like this in the BookEditorContainer:

```
class BookEditorCont extends React.Component<any, any>{

    render() {
        return (
            < BookEditorLoadable
                editDisplayPosition={this.props.editDisplayPosition}
                editorAnimationOn={this.props.editorAnimationOn}
                editPart={this.props.editPart}
            />
        )
    }
}
```
The trace statement in the loading component  triggers `Loading component:  true null false`  but the component never materializes. Here is a snapshot of the React Chrome dev tools.

![screen shot 2017-03-21 at 12 55 53 pm](https://cloud.githubusercontent.com/assets/16655922/24159615/ed3a892c-0e35-11e7-9d92-9fd4cd64e72e.png)

Any ideas?
Thank you.

**Comment by thejameskyle** [comment]
I'm not sure, maybe look into your network tab in devtools to see the requests being made. Also might want to try inspecting what `System.import` is doing in the generated code by stepping through it in the debugger. As long as it's returning a promise that will eventually resolve or reject, react-loadable should be doing its thing just fine.

**Comment by thejameskyle** [comment]
I'm going to close this because otherwise these issues have a tendency to stay open forever. If you don't figure it out, let me know.

**Comment by maierson** [comment]
The script downloads and the promise seems to resolve. 

![screen shot 2017-03-21 at 3 17 52 pm](https://cloud.githubusercontent.com/assets/16655922/24166488/c88183ec-0e49-11e7-9918-762533f6bbbb.png)

**Comment by thejameskyle** [comment]
Oh, it's probably that it's not the default export. Right now react-loadable only handles that

**Comment by maierson** [comment]
That was it. Thank you! Works great.

One last question - is there a callback for when the component has finished loading?

**Comment by thejameskyle** [comment]
Other than the component itself loading? What do you need it for?

**Comment by maierson** [comment]
Good point. I need to apply some css transitions to the component's parent once it is available and only execute once I am sure to have it.

**Comment by thejameskyle** [comment]
If you want to open an issue with a detailed example of what you're trying to do I can look into it

**Comment by maierson** [comment]
Thank you James. For now it all works well by preloading the component right after the initial app bundle. I think that I can work with `componentDidMount` in case I run into a need for more complicated timing. This is already a huge benefit.
