### ISSUE TITLE
setState calls on unmounted component

### ISSUE THREAD

**Issue by istarkov** [thejameskyle/react-loadable#4]
[here](https://github.com/thejameskyle/react-loadable/blob/461c4e9cb7ddb813c08373d32a3fc29e96dff73e/src/index.js#L63) and [here](https://github.com/thejameskyle/react-loadable/blob/461c4e9cb7ddb813c08373d32a3fc29e96dff73e/src/index.js#L70)

Both calls can cause an error if component is unmounted.

**Comment by thejameskyle** [comment]
Fixed in https://github.com/thejameskyle/react-loadable/commit/95a472cadfa60c237e3c5cdf6a5542691552f1e7
